# frozen_string_literal: true

module Prospect
  module Emit
    # IR -> TypeScript declarations. Emits **types only** — no client, no
    # methods, no logic (DESIGN.md §7). The runtime client is hand-written,
    # versioned and generic over the `Procedures` map, so regenerating this file
    # produces a legible diff instead of a rewritten 2000-line client.
    module TypeScript
      SCALARS = {
        "string" => "string", "int" => "number", "float" => "number",
        "bool" => "boolean", "decimal" => "string",
        # RFC 3339 UTC, pinned by the dispatcher. A string, not Date: JSON has no
        # date type and silently reviving one is how clients start disagreeing.
        "timestamp" => "string", "date" => "string",
        "uuid" => "string", "bytes" => "string", "null" => "null", "void" => "void"
      }.freeze

      class << self
        def call(ir)
          [header, schema_hash(ir), types(ir), procedures(ir), errors(ir),
           wire_maps(ir), proc_types(ir), error_codes(ir)].compact.join("\n")
        end

        private

        def header
          <<~TS
            // Generated by `prospect emit ts` — do not edit.
            //
            // Types only, by design: the runtime client is hand-written and generic
            // over `Procedures` below. Field names are camelCase here and snake_case
            // on the wire; the client's generated mappers handle that, and they do
            // NOT touch map keys, which are data.

          TS
        end

        # The client sends this on every request so the server can tell it was
        # generated against a different contract — the only drift check that
        # survives past build time, since a cached browser bundle type-checked
        # perfectly well when it was built. DESIGN.md §4.
        def schema_hash(ir)
          %(export const SCHEMA_HASH = "#{ir['schema_hash']}"\n)
        end

        def types(ir)
          ir["types"].map { |name, defn|
            fields = defn["fields"].map { |f|
              opt = f["default"] || f["type"]["kind"] == "optional" ? "?" : ""
              "  #{camel(f['name'])}#{opt}: #{ts(f['type'])}"
            }
            "export interface #{name} {\n#{fields.join("\n")}\n}"
          }.join("\n\n") + "\n"
        end

        def procedures(ir)
          rows = ir["procedures"].map do |p|
            errs = p["errors"].map { |e| e["name"] }
            err = errs.empty? ? "never" : errs.join(" | ")
            %(  "#{p['path']}": { kind: "#{p['kind']}"; input: #{ts(p['input'])}; ) +
              %(output: #{ts(p['output'])}; error: #{err} })
          end
          "\nexport type Procedures = {\n#{rows.join("\n")}\n}\n"
        end

        def errors(ir)
          declared = ir["procedures"].flat_map { |p| p["errors"] }.uniq { |e| e["name"] }
          return nil if declared.empty?

          decls = declared.map { |e|
            fields = e["fields"].map { |f| "  #{camel(f)}: string" }
            body = (['  code: "' + e["code"] + '"'] + fields).join("\n")
            "export interface #{e['name']} {\n#{body}\n}"
          }
          "\n#{decls.join("\n\n")}\n"
        end

        # Per-type field rename tables, plus which fields hold nested structs so
        # the client can recurse.
        #
        # This is the alternative to a generic deep-camelize, which cannot tell a
        # struct field (rename it) from a map key (user data — don't). Only names
        # listed here are ever touched, so `reactionCounts`'s emoji keys and
        # `ValidationFailed.errors`'s field keys pass through untouched by
        # construction rather than by care. DESIGN.md §7.
        # The IR knows every procedure's input and output type. Emitting the
        # table means the client never guesses — an earlier hand-maintained
        # version of this in bookface's client was the one thing guaranteed to
        # drift.
        def proc_types(ir)
          rows = ir["procedures"].map { |p|
            %(  "#{p['path']}": { input: "#{p['input']['name']}", output: "#{p['output']['name']}" },)
          }
          <<~TS

            /** Input/output type per procedure, so the client can map both directions. */
            export const PROC_TYPES: Record<string, { input: string; output: string }> = {
            #{rows.join("\n")}
            }
          TS
        end

        # Wire code -> error interface, so a failure response can be mapped the
        # same way a success one is. Without this an error's fields stay
        # snake_case while its declared TS interface says camelCase.
        def error_codes(ir)
          declared = ir["procedures"].flat_map { |p| p["errors"] }.uniq { |e| e["name"] }
          return nil if declared.empty?

          rows = declared.map { |e| %(  #{e['code']}: "#{e['name']}",) }
          <<~TS

            /** Wire error code -> interface name. */
            export const ERROR_TYPES: Record<string, string> = {
            #{rows.join("\n")}
            }
          TS
        end

        def wire_maps(ir)
          renames = {}
          nested  = {}

          # Errors are structs on the wire too, and need the same treatment.
          # Note their map-valued fields (ValidationFailed#errors, keyed by field
          # name) are absent from `nested`, so their keys are never touched.
          ir["procedures"].flat_map { |p| p["errors"] }.uniq { |e| e["name"] }.each do |e|
            r = e["fields"].to_h { |f| [camel(f), f] }.reject { |c, w| c == w }
            renames[e["name"]] = r if r.any?
          end

          ir["types"].each do |name, defn|
            r = defn["fields"].to_h { |f| [camel(f["name"]), f["name"]] }
                              .reject { |camel_name, wire| camel_name == wire }
            renames[name] = r if r.any?

            n = defn["fields"].filter_map { |f|
              ref = ref_name(f["type"])
              [camel(f["name"]), ref] if ref
            }.to_h
            nested[name] = n if n.any?
          end

          <<~TS

            /** camelCase -> wire name, per type. Nothing else is renamed. */
            export const WIRE_FIELDS: Record<string, Record<string, string>> = #{json(renames)}

            /** Fields holding a nested struct (or list of one), for recursion. */
            export const WIRE_NESTED: Record<string, Record<string, string>> = #{json(nested)}
          TS
        end

        # Unwraps optional/list to find a struct ref, if there is one. A `map`
        # node deliberately returns nil — its values are not renamed.
        def ref_name(node)
          case node["kind"]
          when "ref"               then node["name"]
          when "optional", "list"  then ref_name(node["of"])
          end
        end

        def json(hash)
          return "{}" if hash.empty?

          rows = hash.map { |type, fields|
            inner = fields.map { |k, v| %(#{k}: "#{v}") }.join(", ")
            "  #{type}: { #{inner} },"
          }
          "{\n#{rows.join("\n")}\n}"
        end

        def ts(node)
          case node["kind"]
          when "scalar"   then SCALARS.fetch(node["name"])
          when "ref"      then node["name"]
          when "list"     then "#{ts(node['of'])}[]"
          when "optional" then "#{ts(node['of'])} | null"
          when "union"    then node["of"].map { |n| ts(n) }.join(" | ")
          when "enum"     then node["values"].map { |v| %("#{v}") }.join(" | ")
          when "map"
            # Record<K, V> — an index signature, so keys stay untouched. This is
            # the node that stops a deep-camelize mangling emoji or field-name
            # keys (DESIGN.md §7).
            "Record<#{ts(node['key'])}, #{ts(node['value'])}>"
          else raise "unknown IR node #{node['kind']}"
          end
        end

        def camel(name)
          head, *rest = name.split("_")
          [head, *rest.map(&:capitalize)].join
        end
      end
    end
  end
end
