// Generated by `prospect emit ts` — do not edit.
//
// Types only, by design: the runtime client is hand-written and generic
// over `Procedures` below. Field names are camelCase here and snake_case
// on the wire; the client's generated mappers handle that, and they do
// NOT touch map keys, which are data.


export interface Ping {
  who: string
  loud?: boolean
}

export interface Matrix {
  str: string
  int: number
  flt: number
  flag: boolean
  at: string
  on: string
  money: string
  maybe?: string | null
  list: string[]
  refs: Nested[]
  lookup: Record<string, number>
  nested: Nested
  colour: "red" | "blue"
  tree: Tree
  withDefault?: string
  twoWords: string
}

export interface Nested {
  label: string
}

export interface Tree {
  label: string
  children?: Tree[]
}

export interface Empty {

}


export type Procedures = {
  "echo.boom": { kind: "query"; input: Empty; output: Empty; error: NotFound }
  "echo.explode": { kind: "query"; input: Empty; output: Empty; error: never }
  "echo.ping": { kind: "query"; input: Ping; output: Matrix; error: never }
  "echo.secret": { kind: "query"; input: Empty; output: Empty; error: never }
  "other.touch": { kind: "mutation"; input: Empty; output: Empty; error: never }
}


export interface NotFound {
  code: "not_found"
  resource: string
  id: string
}


/** camelCase -> wire name, per type. Nothing else is renamed. */
export const WIRE_FIELDS: Record<string, Record<string, string>> = {
  Matrix: { withDefault: "with_default", twoWords: "two_words" },
}

/** Fields holding a nested struct (or list of one), for recursion. */
export const WIRE_NESTED: Record<string, Record<string, string>> = {
  Matrix: { refs: "Nested", nested: "Nested", tree: "Tree" },
  Tree: { children: "Tree" },
}


/** Input/output type per procedure, so the client can map both directions. */
export const PROC_TYPES: Record<string, { input: string; output: string }> = {
  "echo.boom": { input: "Empty", output: "Empty" },
  "echo.explode": { input: "Empty", output: "Empty" },
  "echo.ping": { input: "Ping", output: "Matrix" },
  "echo.secret": { input: "Empty", output: "Empty" },
  "other.touch": { input: "Empty", output: "Empty" },
}


/** Wire error code -> interface name. */
export const ERROR_TYPES: Record<string, string> = {
  not_found: "NotFound",
}
